import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@/styles/globals.scss'
import { NotificationsProvider } from '@providers/NotificationsProvider'
import { PropsWithChildren } from 'react'
import { Notifications } from '@entities/Notifications'
import { ScrollToTop } from '@providers/ScrollToTop'
import { SessionProvider } from '@providers/SessionProvider'
import { CookiesProvider } from 'next-client-cookies/server'

const montserrat = Montserrat({ subsets: ['cyrillic', 'latin'] })

export const metadata: Metadata = {
  title: 'Ремесло',
  description: 'Generated by create next app',
  icons: {
    icon: 'favicon.ico'
  }
}

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <SessionProvider>
          <div id='root'>
            <ScrollToTop>
              <CookiesProvider>
                <NotificationsProvider>
                  <Notifications />
                  {children}
                </NotificationsProvider>
              </CookiesProvider>
            </ScrollToTop>
          </div>
        </SessionProvider>
      </body>
    </html >
  )
}
